name: Migrate DB (prod) and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci
      - run: npx prisma generate

      # 本番DBへマイグレーション適用（5432直結）
      - name: Prisma migrate deploy (prod)
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}

